Fix ci

diff --git a/.github/workflows/check-code-quality.yml b/.github/workflows/check-code-quality.yml
--- a/.github/workflows/check-code-quality.yml
+++ b/.github/workflows/check-code-quality.yml
@@ -88,17 +88,23 @@ jobs:
       security-events: write # needed for github/codeql-action/upload-sarif
     steps:
       - uses: actions/checkout@v6
-      - uses: ./.github/actions/poetry-install
-        with:
-          rm-plugin-dir: true
+
+      # NOTE: install tools with pip install, not with poetry,
+      # because the pyproject.toml needs to git clone the sub-repositories: rs-server, rs-client-libraries, ...
+      - name: Pip install tools
+        run: |
+          set -x
+          pip install "bandit==1.9.1" "safety==3.6.0" \
+            "typer==0.16.0" # version compatible with safety
+        shell: bash
 
       - id: bandit
         name: Run bandit
         if: always() # even if previous steps returned a non-zero exit code
         run: |
           set -x
-          poetry run bandit -c pyproject.toml -r . || true # run next line even if fails
-          poetry run bandit -c pyproject.toml -r . -f json -o ./bandit-report.json
+          bandit -c pyproject.toml -r . || true # run next line even if fails
+          bandit -c pyproject.toml -r . -f json -o ./bandit-report.json
         shell: bash
 
       - id: safety
@@ -108,7 +114,7 @@ jobs:
             SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
         run: |
           set -x
-          poetry run safety --key $SAFETY_API_KEY scan --detailed-output
+          safety --key $SAFETY_API_KEY scan --detailed-output
         shell: bash
 
       - name: Run Trivy vulnerability scanner
